language: php

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

php:
  - '5.6'
  - '7.0'

before_script:
  - composer self-update
  - composer install --no-dev
  - php tools/cliinstall.php --db=glpitest --user=root --tests --type=$DB

script:
 - mysql -u root -e 'select version();'
 - phpunit --verbose

#matrix:
#  include:
#    - php: 5.6
#      addons:
#        mariadb: 5.5
#    - php: 5.6
#      addons:
#        mariadb: 10.0
#    - php: 5.6
#      addons:
#        mariadb: 10.1
#    - php: 7.0
#      addons:
#        mariadb: 10.0
#    - php: 7.0
#      addons:
#        mariadb: 10.1
#    - php: nightly
#      addons:
#        mariadb: 10.1
#  allow_failures:
#    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "irc.freenode.org#glpi"
    on_success: change
    on_failure: always

#exclude old branches, without tests
branches:
  except:
    - /^0\..*$/
